{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "copilot.serviceAccountName" . }}
  labels: {{- include "copilot.labels" . | nindent 4 }}
{{- end }}
